---
- name: Set up webserver
  hosts: webservers
  become: yes

  tasks:
  - name: Install Apache Webserver
    yum:
      name: httpd
      state: present

  - name: Opening http port
    firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes

 # - name: Restarting http
 #   systemd:
 #     service: httpd
 #     state: restarted
 #     enabled: no

  - name: reload firewalld
    systemd:
      service: firewalld
      state: restarted
      
